### ISSUE TITLE
Extraer de la guía de estudio las sentencias de Git para trabajar en VSC.

### ISSUE THREAD

**Issue by danielasgomez273** [gabi156156/Aula-36-Ispc#15]
Extraer del libro 2. GITHUB - VSC, correspondiente a la Guía de estudio Metodologías Agiles y Gestión de Proyectos las sentencias de Git con las que trabajaremos en VSC.

**Comment by DHerrera85** [comment]
Agregadas las sentencias de VSC del material de estudio a read.me

**Comment by danielasgomez273** [comment]
@rominadma algún aporte para agregar? Esperamos tus comentarios.

**Comment by danielasgomez273** [comment]
Tarea finalizada
