### ISSUE TITLE
Resumir de la guía de estudio el paso a paso para trabajar en Git

### ISSUE THREAD

**Issue by danielasgomez273** [gabi156156/Aula-36-Ispc#16]
Extraer del libro 4. GIT, correspondiente a la Guía de estudio Metodologías Agiles y Gestión de Proyectos el paso a paso para trabajar en Git (clonar repositorio, crear ramas, subir modificaciones, etc)

**Comment by DHerrera85** [comment]
Se actualiza documento quitando texto duplicado
