### ISSUE TITLE
Subir en la rama personal archivo CV - Romina

### ISSUE THREAD

**Issue by danielasgomez273** [gabi156156/Aula-36-Ispc#23]
Subir CV en formato PDF.

**Comment by rominadma** [comment]
[CamScanner 06-28-2022 20.09.pdf](https://github.com/danielasgomez273/Aula-36-Ispc/files/9054241/CamScanner.06-28-2022.20.09.pdf)

**Comment by rominadma** [comment]
Curriculum

**Comment by danielasgomez273** [comment]
Hola @rominadma! Sería recomendable renombrar el PDF con el formato "nombre apellido CV" o "CV nombre apellido", como habíamos hablado en las reuniones. Saludos,

**Comment by danielasgomez273** [comment]
Tarea finalizada
