### ISSUE TITLE
Extraer de la guía los comandos GIT - GITHUB

### ISSUE THREAD

**Issue by martin-delhugo** [gabi156156/Aula-36-Ispc#3]
Crear un documento simple que tenga los comandos de git y github para tenerlos a mano en caso de necesitarlos.

**Comment by danielasgomez273** [comment]
Extraer comandos del libro 3. GIT y GITHUB, correspondiente a la Guía de estudio Metodologías Agiles y Gestión de Proyectos.

**Comment by danielasgomez273** [comment]
@angelcarballeira @Fgavier algo más para agregar? Esperamos sus comentarios.

**Comment by danielasgomez273** [comment]
Se considera tarea finalizada
